# Generated by Django 4.2.1 on 2023-05-29 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='course/'),
            preserve_default=False,
        ),
    ]
