# Generated by Django 5.0.3 on 2024-08-08 20:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("percentage", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.FileField(upload_to="competence/")),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("the_year", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_complete",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatar/"),
                ),
                (
                    "mini_about",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("about", django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text")),
                ("born_date", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("cv", models.FileField(blank=True, null=True, upload_to="cv")),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255)),
                ("message", models.TextField()),
                ("send_time", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logo/")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("the_year", models.CharField(max_length=50)),
                (
                    "stack",
                    models.ManyToManyField(
                        blank=True, related_name="stack", to="information.competence"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("image", models.ImageField(upload_to="projects/")),
                ("demo", models.URLField()),
                ("github", models.URLField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "all"),
                            (2, "live"),
                            (3, "upcoming"),
                            (4, "in_progress"),
                        ],
                        verbose_name="stado",
                    ),
                ),
                ("show_in_slider", models.BooleanField(default=False)),
                (
                    "tools",
                    models.ManyToManyField(
                        max_length=200,
                        related_name="tools",
                        to="information.competence",
                    ),
                ),
            ],
        ),
    ]
