# Generated by Django 5.2.7 on 2026-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='admin_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='admin_signed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='client_signed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending-admin-signature', 'Pending Admin Signature'), ('pending-client-signature', 'Pending Client Signature'), ('pending-signature', 'Pending Signature'), ('signed', 'Signed'), ('expired', 'Expired')], default='draft', max_length=30),
        ),
    ]
