# Generated by Django 5.2.7 on 2026-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_document_admin_signed_at_document_admin_signed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content of the document', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded document file', null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
