# Generated by Django 5.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_add_user_authentication'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='project_inquiry',
        ),
        migrations.RemoveField(
            model_name='clientaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientAccount',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
