# Generated by Django 5.1 on 2025-11-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_add_dashboard_models'),
        ('information', '0005_remove_auth_models'),
    ]

    operations = [
    ]
